### ISSUE TITLE
Electron Version 11 **FAILS**

### ISSUE THREAD

**Issue by snaildos** [snaildos/SnailFM-Application#8]
`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.16.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle SnailFM@1.1.3~prestart: SnailFM@1.1.3
6 info lifecycle SnailFM@1.1.3~start: SnailFM@1.1.3
7 verbose lifecycle SnailFM@1.1.3~start: unsafe-perm in lifecycle true
8 verbose lifecycle SnailFM@1.1.3~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\zaras\Documents\GitHub\SnailFM-Application\node_modules\.bin;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\compiler;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs\;F:\Program Files\GnuWin32\bin;F:\Program Files\putty\;C:\Program Files\dotnet\;F:\Program Files\Yarn\bin\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Git\cmd;F:\Gradlew\bin;C:\Users\zaras\AppData\Local\Programs\Python\Python37-32\Scripts\;C:\Users\zaras\AppData\Local\Programs\Python\Python37-32\;C:\Users\zaras\AppData\Local\Microsoft\WindowsApps;C:\Users\zaras\AppData\Roaming\npm;C:\Users\zaras\AppData\Local\GitHubDesktop\bin;F:\Program Files\Microsoft VS Code\bin;C:\Path;C:\Program Files\heroku\bin;F:\Program Files\heroku\bin;C:\Users\zaras\AppData\Local\Yarn\bin;C:\Users\zaras\AppData\Local\Microsoft\WindowsApps
9 verbose lifecycle SnailFM@1.1.3~start: CWD: C:\Users\zaras\Documents\GitHub\SnailFM-Application
10 silly lifecycle SnailFM@1.1.3~start: Args: [ '/d /s /c', 'electron .' ]
11 silly lifecycle SnailFM@1.1.3~start: Returned: code: 4294930435  signal: null
12 info lifecycle SnailFM@1.1.3~start: Failed to exec start script
13 verbose stack Error: SnailFM@1.1.3 start: `electron .`
13 verbose stack Exit status 4294930435
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:310:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:310:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid SnailFM@1.1.3
15 verbose cwd C:\Users\zaras\Documents\GitHub\SnailFM-Application
16 verbose Windows_NT 10.0.19041
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v12.16.2
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 4294930435
22 error SnailFM@1.1.3 start: `electron .`
22 error Exit status 4294930435
23 error Failed at the SnailFM@1.1.3 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 4294930435, true ]
`

**Comment by snaildos** [comment]
Resolved in latest.
Downgraded back too older electron.
